name: Reset Billing Cycles

on:
  schedule:
    # Run daily at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  reset-billing-cycles:
    runs-on: [my-runners-6]
    
    steps:
      - name: Call Reset Billing Cycles Function
        env:
          SUPABASE_ANON_KEY: ${{ secrets.SUPABASE_ANON_KEY }}
        run: |
          response=$(curl -s -X POST \
            "https://azcoimamdsdsyjqsduaizxgn.supabase.co/functions/v1/reset-billing-cycles" \
            -H "Authorization: Bearer $SUPABASE_ANON_KEY" \
            -H 'Content-Type: application/json' \
            --data '{"name":"Functions"}')
          
          if [[ $(echo $response | jq -r .success) == "true" ]]; then
            echo "Successfully reset billing cycles"
            echo "Response: $response"
          else
            echo "Failed to reset billing cycles"
            echo "Response: $response"
            exit 1
          fi

      - name: Log Result
        run: echo "Billing cycles reset job completed"