name: Basic Test Workflow

on:
  schedule:
    # Run daily at 2 AM UTC (adjust timezone as needed)
    - cron: '0 2 * * *'
  workflow_dispatch: # Allow manual trigger

jobs:
  test:
    runs-on: [small]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Print success message
      run: echo "hey this worked"

    - uses: actions/checkout@v4 # Checks out your repository code
      name: Checkout Code

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20' # Specifies the Node.js version

    - name: Install dependencies
      run: npm install

